### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by deaniliev** [tsvetelintsonev/php-http-virtualmin-api#4]
Hi,

When I try to install it using composer, it returns the following:

- nilemin/php-http-virtualmin-api v1.0.0 requires guzzlehttp/guzzle 6.2.1 -> satisfiable by guzzlehttp/guzzle[6.2.1] but these conflict with your requirements or minimum-stability.

My guzzlehttp/guzzle is 6.5. I guess composer.json needs an update.

Best regards,

**Comment by miguel456** [comment]
Hi,

You're right, composer.json does need an update to the newest Guzzle version.

My recommendation is that you downgrade Guzzle to 6.2.1 in your composer.json, but this might cause a chain reaction of version incompatibilities if the packages that depend on Guzzle aren't lax with their version requirements, or require a very specific version and only that version such as 6.5.

Please let me know if you have any more questions!

Regards,
Miguel N
